@echo off
setlocal EnableDelayedExpansion
:: AutoJobApplier — one-command setup for Windows
:: Usage: setup.bat (double-click or run from Command Prompt)

echo.
echo  ====================================================
echo   AutoJobApplier Setup
echo  ====================================================
echo.

:: ── Check Docker ──────────────────────────────────────────────────────────
docker info >nul 2>&1
if errorlevel 1 (
    echo [ERROR] Docker is not running or not installed.
    echo   Get Docker Desktop at: https://docs.docker.com/get-docker/
    pause
    exit /b 1
)
echo [OK] Docker is running

:: ── Check Python ──────────────────────────────────────────────────────────
python --version >nul 2>&1
if errorlevel 1 (
    echo [ERROR] Python is not installed. Get it at https://python.org
    pause
    exit /b 1
)
echo [OK] Python found

:: ── Generate .env ─────────────────────────────────────────────────────────
if exist .env (
    echo [SKIP] .env already exists - skipping secret generation.
    echo        Delete .env and re-run to regenerate secrets.
) else (
    echo.
    echo Generating secrets...

    :: Generate secrets using Python
    for /f %%i in ('python -c "import secrets; print(secrets.token_urlsafe(64))"') do set SECRET_KEY=%%i
    for /f %%i in ('python -c "import secrets; print(secrets.token_urlsafe(24))"') do set DB_PASSWORD=%%i
    for /f %%i in ('python -c "import secrets; print(secrets.token_urlsafe(24))"') do set REDIS_PASSWORD=%%i
    python -c "from cryptography.fernet import Fernet; print(Fernet.generate_key().decode())" >nul 2>&1
    if errorlevel 1 (
        for /f %%i in ('python -c "import base64,os; print(base64.urlsafe_b64encode(os.urandom(32)).decode())"') do set FERNET_KEY=%%i
    ) else (
        for /f %%i in ('python -c "from cryptography.fernet import Fernet; print(Fernet.generate_key().decode())"') do set FERNET_KEY=%%i
    )

    (
        echo # Auto-generated by setup.bat -- do NOT commit this file
        echo.
        echo # App
        echo ENVIRONMENT=development
        echo LOG_LEVEL=INFO
        echo.
        echo # Database
        echo DB_NAME=autojobapplier
        echo DB_USER=postgres
        echo DB_PASSWORD=!DB_PASSWORD!
        echo.
        echo # Redis
        echo REDIS_PASSWORD=!REDIS_PASSWORD!
        echo.
        echo # Security
        echo SECRET_KEY=!SECRET_KEY!
        echo DATABASE_ENCRYPTION_KEY=!FERNET_KEY!
        echo.
        echo # LLM (optional -- leave blank)
        echo ANTHROPIC_API_KEY=
        echo.
        echo # Frontend
        echo NEXT_PUBLIC_API_URL=http://localhost:8000
        echo NEXTAUTH_URL=http://localhost:3000
        echo NEXTAUTH_SECRET=!SECRET_KEY!
    ) > .env

    echo [OK] .env generated with random secrets
)

:: ── Build and start ────────────────────────────────────────────────────────
echo.
echo Building Docker images (first run takes 3-5 minutes)...
docker compose build --parallel
if errorlevel 1 (
    echo [ERROR] Docker build failed. See errors above.
    pause
    exit /b 1
)

echo.
echo Starting services...
docker compose up -d
if errorlevel 1 (
    echo [ERROR] Failed to start services.
    pause
    exit /b 1
)

:: ── Wait for backend ───────────────────────────────────────────────────────
echo.
echo Waiting for backend to be ready...
set ATTEMPTS=0
:WAIT_LOOP
set /a ATTEMPTS+=1
if !ATTEMPTS! GTR 40 (
    echo.
    echo [ERROR] Backend did not start within 2 minutes.
    echo         Check logs: docker compose logs backend
    pause
    exit /b 1
)
curl -sf http://localhost:8000/health >nul 2>&1
if errorlevel 1 (
    timeout /t 3 /nobreak >nul
    set /p =.<nul
    goto WAIT_LOOP
)

:: ── Done ──────────────────────────────────────────────────────────────────
echo.
echo.
echo  ====================================================
echo   AutoJobApplier is running!
echo  ====================================================
echo   App:  http://localhost:3000
echo   API:  http://localhost:8000/docs
echo  ====================================================
echo.
echo  Next steps:
echo   1. Open http://localhost:3000
echo   2. Register an account
echo   3. Go to Resumes and add your .tex resume files
echo   4. Fill in your Profile
echo   5. Paste a job URL or import from Handshake CSV
echo.
echo  Useful commands:
echo   View logs:  docker compose logs -f
echo   Stop:       docker compose down
echo   Reset all:  docker compose down -v
echo.
pause
