#!/usr/bin/env bash
# AutoJobApplier — one-command setup
# Usage: bash setup.sh
set -euo pipefail

BOLD='\033[1m'; CYAN='\033[0;36m'; GREEN='\033[0;32m'; RED='\033[0;31m'; NC='\033[0m'

header()  { echo -e "\n${CYAN}${BOLD}▶ $1${NC}"; }
success() { echo -e "${GREEN}✓ $1${NC}"; }
error()   { echo -e "${RED}✗ $1${NC}"; exit 1; }

header "AutoJobApplier Setup"
echo "This script generates secrets and starts all services."
echo "Run it once. After that, use: docker compose up"

# ── Prerequisite checks ──────────────────────────────────────────────────────
header "Checking prerequisites"

command -v docker   >/dev/null 2>&1 || error "Docker is not installed. Get it at https://docs.docker.com/get-docker/"
command -v python3  >/dev/null 2>&1 || error "Python 3 is required to generate secrets."

docker info >/dev/null 2>&1 || error "Docker daemon is not running. Start Docker Desktop and re-run."
success "Docker is running"

# ── Generate .env ────────────────────────────────────────────────────────────
header "Generating .env"

if [ -f .env ]; then
  echo "  .env already exists — skipping secret generation."
  echo "  Delete .env and re-run setup.sh to regenerate secrets."
else
  # Generate cryptographically random values
  SECRET_KEY=$(python3 -c "import secrets; print(secrets.token_urlsafe(64))")
  DB_PASSWORD=$(python3 -c "import secrets; print(secrets.token_urlsafe(24))")
  REDIS_PASSWORD=$(python3 -c "import secrets; print(secrets.token_urlsafe(24))")
  FERNET_KEY=$(python3 -c "from cryptography.fernet import Fernet; print(Fernet.generate_key().decode())" 2>/dev/null \
               || python3 -c "import base64, os; print(base64.urlsafe_b64encode(os.urandom(32)).decode())")

  cat > .env <<EOF
# Auto-generated by setup.sh — do NOT commit this file

# ── App ───────────────────────────────────────────────────────────────────────
ENVIRONMENT=development
LOG_LEVEL=INFO

# ── Database ──────────────────────────────────────────────────────────────────
DB_NAME=autojobapplier
DB_USER=postgres
DB_PASSWORD=${DB_PASSWORD}

# ── Redis ─────────────────────────────────────────────────────────────────────
REDIS_PASSWORD=${REDIS_PASSWORD}

# ── Security ──────────────────────────────────────────────────────────────────
SECRET_KEY=${SECRET_KEY}
DATABASE_ENCRYPTION_KEY=${FERNET_KEY}

# ── LLM (optional — leave blank, not required) ───────────────────────────────
ANTHROPIC_API_KEY=

# ── Frontend ──────────────────────────────────────────────────────────────────
NEXT_PUBLIC_API_URL=http://localhost:8000
NEXTAUTH_URL=http://localhost:3000
NEXTAUTH_SECRET=${SECRET_KEY}
EOF

  success ".env generated with random secrets"
fi

# ── Build and start ──────────────────────────────────────────────────────────
header "Building Docker images (first run takes 3-5 minutes)"
docker compose build --parallel

header "Starting services"
docker compose up -d

# ── Wait for healthy ─────────────────────────────────────────────────────────
header "Waiting for backend to be ready"
ATTEMPTS=0
MAX=40
until curl -sf http://localhost:8000/health >/dev/null 2>&1; do
  ATTEMPTS=$((ATTEMPTS+1))
  if [ $ATTEMPTS -ge $MAX ]; then
    echo ""
    error "Backend did not start within 2 minutes. Check logs: docker compose logs backend"
  fi
  printf "."
  sleep 3
done
echo ""
success "Backend is ready"

# ── Done ─────────────────────────────────────────────────────────────────────
echo ""
echo -e "${GREEN}${BOLD}╔══════════════════════════════════════════════════╗${NC}"
echo -e "${GREEN}${BOLD}║  AutoJobApplier is running!                      ║${NC}"
echo -e "${GREEN}${BOLD}╠══════════════════════════════════════════════════╣${NC}"
echo -e "${GREEN}${BOLD}║  App:    http://localhost:3000                    ║${NC}"
echo -e "${GREEN}${BOLD}║  API:    http://localhost:8000/docs               ║${NC}"
echo -e "${GREEN}${BOLD}║                                                  ║${NC}"
echo -e "${GREEN}${BOLD}║  Next steps:                                     ║${NC}"
echo -e "${GREEN}${BOLD}║  1. Open http://localhost:3000                    ║${NC}"
echo -e "${GREEN}${BOLD}║  2. Register an account                          ║${NC}"
echo -e "${GREEN}${BOLD}║  3. Go to Resumes → Add Resume (.tex files)      ║${NC}"
echo -e "${GREEN}${BOLD}║  4. Fill in your Profile                         ║${NC}"
echo -e "${GREEN}${BOLD}║  5. Paste a job URL to start                     ║${NC}"
echo -e "${GREEN}${BOLD}╚══════════════════════════════════════════════════╝${NC}"
echo ""
echo "Logs:    docker compose logs -f"
echo "Stop:    docker compose down"
echo "Reset:   docker compose down -v  (wipes data)"
